/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SessionLockedRouteImport } from './routes/session-locked'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as R2faRouteImport } from './routes/2fa'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as Error500RouteImport } from './routes/error.500'
import { Route as Error404RouteImport } from './routes/error.404'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as MarketingApiDocsRouteImport } from './routes/_marketing/api-docs'
import { Route as MarketingSlugRouteImport } from './routes/_marketing/$slug'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPlatformsRouteImport } from './routes/_app/platforms'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppEstablishmentsRouteImport } from './routes/_app/establishments'
import { Route as AppEReportingRouteImport } from './routes/_app/e-reporting'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppComplianceRouteImport } from './routes/_app/compliance'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppAgentRouteImport } from './routes/_app/agent'
import { Route as AppTeamIndexRouteImport } from './routes/_app/team.index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices.index'
import { Route as AppBillingIndexRouteImport } from './routes/_app/billing.index'
import { Route as MarketingPagesSlugRouteImport } from './routes/_marketing/pages.$slug'
import { Route as AppTeamRolesRouteImport } from './routes/_app/team.roles'
import { Route as AppTeamPermissionsRouteImport } from './routes/_app/team.permissions'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices.new'
import { Route as AppInvoicesIdRouteImport } from './routes/_app/invoices.$id'
import { Route as AppInboxIdRouteImport } from './routes/_app/inbox.$id'
import { Route as AppClientsNewRouteImport } from './routes/_app/clients.new'
import { Route as AppBillingPlansRouteImport } from './routes/_app/billing.plans'
import { Route as AppBillingHistoryRouteImport } from './routes/_app/billing.history'
import { Route as AppTeamMembersMembershipIdRouteImport } from './routes/_app/team.members.$membershipId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionLockedRoute = SessionLockedRouteImport.update({
  id: '/session-locked',
  path: '/session-locked',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const R2faRoute = R2faRouteImport.update({
  id: '/2fa',
  path: '/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const Error500Route = Error500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => ErrorRoute,
} as any)
const Error404Route = Error404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => ErrorRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingApiDocsRoute = MarketingApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSlugRoute = MarketingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformsRoute = AppPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppEstablishmentsRoute = AppEstablishmentsRouteImport.update({
  id: '/establishments',
  path: '/establishments',
  getParentRoute: () => AppRoute,
} as any)
const AppEReportingRoute = AppEReportingRouteImport.update({
  id: '/e-reporting',
  path: '/e-reporting',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamIndexRoute = AppTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppBillingIndexRoute = AppBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppBillingRoute,
} as any)
const MarketingPagesSlugRoute = MarketingPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const AppTeamRolesRoute = AppTeamRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppTeamPermissionsRoute = AppTeamPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AppTeamRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInboxIdRoute = AppInboxIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInboxRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppClientsRoute,
} as any)
const AppBillingPlansRoute = AppBillingPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppBillingHistoryRoute = AppBillingHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppBillingRoute,
} as any)
const AppTeamMembersMembershipIdRoute =
  AppTeamMembersMembershipIdRouteImport.update({
    id: '/members/$membershipId',
    path: '/members/$membershipId',
    getParentRoute: () => AppTeamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/2fa': typeof R2faRoute
  '/': typeof MarketingIndexRoute
  '/error': typeof ErrorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-locked': typeof SessionLockedRoute
  '/signup': typeof SignupRoute
  '/agent': typeof AppAgentRoute
  '/billing': typeof AppBillingRouteWithChildren
  '/clients': typeof AppClientsRouteWithChildren
  '/compliance': typeof AppComplianceRoute
  '/dashboard': typeof AppDashboardRoute
  '/e-reporting': typeof AppEReportingRoute
  '/establishments': typeof AppEstablishmentsRoute
  '/inbox': typeof AppInboxRouteWithChildren
  '/integrations': typeof AppIntegrationsRoute
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/platforms': typeof AppPlatformsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRouteWithChildren
  '/$slug': typeof MarketingSlugRoute
  '/api-docs': typeof MarketingApiDocsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/error/404': typeof Error404Route
  '/error/500': typeof Error500Route
  '/invite/$token': typeof InviteTokenRoute
  '/billing/history': typeof AppBillingHistoryRoute
  '/billing/plans': typeof AppBillingPlansRoute
  '/clients/new': typeof AppClientsNewRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/team/permissions': typeof AppTeamPermissionsRoute
  '/team/roles': typeof AppTeamRolesRoute
  '/pages/$slug': typeof MarketingPagesSlugRoute
  '/billing/': typeof AppBillingIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/team/': typeof AppTeamIndexRoute
  '/team/members/$membershipId': typeof AppTeamMembersMembershipIdRoute
}
export interface FileRoutesByTo {
  '/2fa': typeof R2faRoute
  '/': typeof MarketingIndexRoute
  '/error': typeof ErrorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-locked': typeof SessionLockedRoute
  '/signup': typeof SignupRoute
  '/agent': typeof AppAgentRoute
  '/clients': typeof AppClientsRouteWithChildren
  '/compliance': typeof AppComplianceRoute
  '/dashboard': typeof AppDashboardRoute
  '/e-reporting': typeof AppEReportingRoute
  '/establishments': typeof AppEstablishmentsRoute
  '/inbox': typeof AppInboxRouteWithChildren
  '/integrations': typeof AppIntegrationsRoute
  '/notifications': typeof AppNotificationsRoute
  '/platforms': typeof AppPlatformsRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/$slug': typeof MarketingSlugRoute
  '/api-docs': typeof MarketingApiDocsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/error/404': typeof Error404Route
  '/error/500': typeof Error500Route
  '/invite/$token': typeof InviteTokenRoute
  '/billing/history': typeof AppBillingHistoryRoute
  '/billing/plans': typeof AppBillingPlansRoute
  '/clients/new': typeof AppClientsNewRoute
  '/inbox/$id': typeof AppInboxIdRoute
  '/invoices/$id': typeof AppInvoicesIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/team/permissions': typeof AppTeamPermissionsRoute
  '/team/roles': typeof AppTeamRolesRoute
  '/pages/$slug': typeof MarketingPagesSlugRoute
  '/billing': typeof AppBillingIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/team': typeof AppTeamIndexRoute
  '/team/members/$membershipId': typeof AppTeamMembersMembershipIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/2fa': typeof R2faRoute
  '/_app': typeof AppRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/error': typeof ErrorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-locked': typeof SessionLockedRoute
  '/signup': typeof SignupRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/billing': typeof AppBillingRouteWithChildren
  '/_app/clients': typeof AppClientsRouteWithChildren
  '/_app/compliance': typeof AppComplianceRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/e-reporting': typeof AppEReportingRoute
  '/_app/establishments': typeof AppEstablishmentsRoute
  '/_app/inbox': typeof AppInboxRouteWithChildren
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/invoices': typeof AppInvoicesRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/platforms': typeof AppPlatformsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRouteWithChildren
  '/_marketing/$slug': typeof MarketingSlugRoute
  '/_marketing/api-docs': typeof MarketingApiDocsRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/error/404': typeof Error404Route
  '/error/500': typeof Error500Route
  '/invite/$token': typeof InviteTokenRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_app/billing/history': typeof AppBillingHistoryRoute
  '/_app/billing/plans': typeof AppBillingPlansRoute
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/inbox/$id': typeof AppInboxIdRoute
  '/_app/invoices/$id': typeof AppInvoicesIdRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/team/permissions': typeof AppTeamPermissionsRoute
  '/_app/team/roles': typeof AppTeamRolesRoute
  '/_marketing/pages/$slug': typeof MarketingPagesSlugRoute
  '/_app/billing/': typeof AppBillingIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/team/': typeof AppTeamIndexRoute
  '/_app/team/members/$membershipId': typeof AppTeamMembersMembershipIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/2fa'
    | '/'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/session-locked'
    | '/signup'
    | '/agent'
    | '/billing'
    | '/clients'
    | '/compliance'
    | '/dashboard'
    | '/e-reporting'
    | '/establishments'
    | '/inbox'
    | '/integrations'
    | '/invoices'
    | '/notifications'
    | '/platforms'
    | '/profile'
    | '/settings'
    | '/team'
    | '/$slug'
    | '/api-docs'
    | '/checkout/success'
    | '/error/404'
    | '/error/500'
    | '/invite/$token'
    | '/billing/history'
    | '/billing/plans'
    | '/clients/new'
    | '/inbox/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/team/permissions'
    | '/team/roles'
    | '/pages/$slug'
    | '/billing/'
    | '/invoices/'
    | '/team/'
    | '/team/members/$membershipId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/2fa'
    | '/'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/session-locked'
    | '/signup'
    | '/agent'
    | '/clients'
    | '/compliance'
    | '/dashboard'
    | '/e-reporting'
    | '/establishments'
    | '/inbox'
    | '/integrations'
    | '/notifications'
    | '/platforms'
    | '/profile'
    | '/settings'
    | '/$slug'
    | '/api-docs'
    | '/checkout/success'
    | '/error/404'
    | '/error/500'
    | '/invite/$token'
    | '/billing/history'
    | '/billing/plans'
    | '/clients/new'
    | '/inbox/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/team/permissions'
    | '/team/roles'
    | '/pages/$slug'
    | '/billing'
    | '/invoices'
    | '/team'
    | '/team/members/$membershipId'
  id:
    | '__root__'
    | '/2fa'
    | '/_app'
    | '/_marketing'
    | '/error'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/session-locked'
    | '/signup'
    | '/_app/agent'
    | '/_app/billing'
    | '/_app/clients'
    | '/_app/compliance'
    | '/_app/dashboard'
    | '/_app/e-reporting'
    | '/_app/establishments'
    | '/_app/inbox'
    | '/_app/integrations'
    | '/_app/invoices'
    | '/_app/notifications'
    | '/_app/platforms'
    | '/_app/profile'
    | '/_app/settings'
    | '/_app/team'
    | '/_marketing/$slug'
    | '/_marketing/api-docs'
    | '/checkout/success'
    | '/error/404'
    | '/error/500'
    | '/invite/$token'
    | '/_marketing/'
    | '/_app/billing/history'
    | '/_app/billing/plans'
    | '/_app/clients/new'
    | '/_app/inbox/$id'
    | '/_app/invoices/$id'
    | '/_app/invoices/new'
    | '/_app/team/permissions'
    | '/_app/team/roles'
    | '/_marketing/pages/$slug'
    | '/_app/billing/'
    | '/_app/invoices/'
    | '/_app/team/'
    | '/_app/team/members/$membershipId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R2faRoute: typeof R2faRoute
  AppRoute: typeof AppRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  ErrorRoute: typeof ErrorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionLockedRoute: typeof SessionLockedRoute
  SignupRoute: typeof SignupRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-locked': {
      id: '/session-locked'
      path: '/session-locked'
      fullPath: '/session-locked'
      preLoaderRoute: typeof SessionLockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/2fa': {
      id: '/2fa'
      path: '/2fa'
      fullPath: '/2fa'
      preLoaderRoute: typeof R2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/500': {
      id: '/error/500'
      path: '/500'
      fullPath: '/error/500'
      preLoaderRoute: typeof Error500RouteImport
      parentRoute: typeof ErrorRoute
    }
    '/error/404': {
      id: '/error/404'
      path: '/404'
      fullPath: '/error/404'
      preLoaderRoute: typeof Error404RouteImport
      parentRoute: typeof ErrorRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/api-docs': {
      id: '/_marketing/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof MarketingApiDocsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/$slug': {
      id: '/_marketing/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof MarketingSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/platforms': {
      id: '/_app/platforms'
      path: '/platforms'
      fullPath: '/platforms'
      preLoaderRoute: typeof AppPlatformsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/establishments': {
      id: '/_app/establishments'
      path: '/establishments'
      fullPath: '/establishments'
      preLoaderRoute: typeof AppEstablishmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/e-reporting': {
      id: '/_app/e-reporting'
      path: '/e-reporting'
      fullPath: '/e-reporting'
      preLoaderRoute: typeof AppEReportingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team/': {
      id: '/_app/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof AppTeamIndexRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/billing/': {
      id: '/_app/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof AppBillingIndexRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_marketing/pages/$slug': {
      id: '/_marketing/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof MarketingPagesSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_app/team/roles': {
      id: '/_app/team/roles'
      path: '/roles'
      fullPath: '/team/roles'
      preLoaderRoute: typeof AppTeamRolesRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/_app/team/permissions': {
      id: '/_app/team/permissions'
      path: '/permissions'
      fullPath: '/team/permissions'
      preLoaderRoute: typeof AppTeamPermissionsRouteImport
      parentRoute: typeof AppTeamRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/invoices/$id': {
      id: '/_app/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/inbox/$id': {
      id: '/_app/inbox/$id'
      path: '/$id'
      fullPath: '/inbox/$id'
      preLoaderRoute: typeof AppInboxIdRouteImport
      parentRoute: typeof AppInboxRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppClientsRoute
    }
    '/_app/billing/plans': {
      id: '/_app/billing/plans'
      path: '/plans'
      fullPath: '/billing/plans'
      preLoaderRoute: typeof AppBillingPlansRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/billing/history': {
      id: '/_app/billing/history'
      path: '/history'
      fullPath: '/billing/history'
      preLoaderRoute: typeof AppBillingHistoryRouteImport
      parentRoute: typeof AppBillingRoute
    }
    '/_app/team/members/$membershipId': {
      id: '/_app/team/members/$membershipId'
      path: '/members/$membershipId'
      fullPath: '/team/members/$membershipId'
      preLoaderRoute: typeof AppTeamMembersMembershipIdRouteImport
      parentRoute: typeof AppTeamRoute
    }
  }
}

interface AppBillingRouteChildren {
  AppBillingHistoryRoute: typeof AppBillingHistoryRoute
  AppBillingPlansRoute: typeof AppBillingPlansRoute
  AppBillingIndexRoute: typeof AppBillingIndexRoute
}

const AppBillingRouteChildren: AppBillingRouteChildren = {
  AppBillingHistoryRoute: AppBillingHistoryRoute,
  AppBillingPlansRoute: AppBillingPlansRoute,
  AppBillingIndexRoute: AppBillingIndexRoute,
}

const AppBillingRouteWithChildren = AppBillingRoute._addFileChildren(
  AppBillingRouteChildren,
)

interface AppClientsRouteChildren {
  AppClientsNewRoute: typeof AppClientsNewRoute
}

const AppClientsRouteChildren: AppClientsRouteChildren = {
  AppClientsNewRoute: AppClientsNewRoute,
}

const AppClientsRouteWithChildren = AppClientsRoute._addFileChildren(
  AppClientsRouteChildren,
)

interface AppInboxRouteChildren {
  AppInboxIdRoute: typeof AppInboxIdRoute
}

const AppInboxRouteChildren: AppInboxRouteChildren = {
  AppInboxIdRoute: AppInboxIdRoute,
}

const AppInboxRouteWithChildren = AppInboxRoute._addFileChildren(
  AppInboxRouteChildren,
)

interface AppInvoicesRouteChildren {
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppTeamRouteChildren {
  AppTeamPermissionsRoute: typeof AppTeamPermissionsRoute
  AppTeamRolesRoute: typeof AppTeamRolesRoute
  AppTeamIndexRoute: typeof AppTeamIndexRoute
  AppTeamMembersMembershipIdRoute: typeof AppTeamMembersMembershipIdRoute
}

const AppTeamRouteChildren: AppTeamRouteChildren = {
  AppTeamPermissionsRoute: AppTeamPermissionsRoute,
  AppTeamRolesRoute: AppTeamRolesRoute,
  AppTeamIndexRoute: AppTeamIndexRoute,
  AppTeamMembersMembershipIdRoute: AppTeamMembersMembershipIdRoute,
}

const AppTeamRouteWithChildren =
  AppTeamRoute._addFileChildren(AppTeamRouteChildren)

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppBillingRoute: typeof AppBillingRouteWithChildren
  AppClientsRoute: typeof AppClientsRouteWithChildren
  AppComplianceRoute: typeof AppComplianceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEReportingRoute: typeof AppEReportingRoute
  AppEstablishmentsRoute: typeof AppEstablishmentsRoute
  AppInboxRoute: typeof AppInboxRouteWithChildren
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPlatformsRoute: typeof AppPlatformsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppBillingRoute: AppBillingRouteWithChildren,
  AppClientsRoute: AppClientsRouteWithChildren,
  AppComplianceRoute: AppComplianceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEReportingRoute: AppEReportingRoute,
  AppEstablishmentsRoute: AppEstablishmentsRoute,
  AppInboxRoute: AppInboxRouteWithChildren,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPlatformsRoute: AppPlatformsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MarketingRouteChildren {
  MarketingSlugRoute: typeof MarketingSlugRoute
  MarketingApiDocsRoute: typeof MarketingApiDocsRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingPagesSlugRoute: typeof MarketingPagesSlugRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingSlugRoute: MarketingSlugRoute,
  MarketingApiDocsRoute: MarketingApiDocsRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingPagesSlugRoute: MarketingPagesSlugRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface ErrorRouteChildren {
  Error404Route: typeof Error404Route
  Error500Route: typeof Error500Route
}

const ErrorRouteChildren: ErrorRouteChildren = {
  Error404Route: Error404Route,
  Error500Route: Error500Route,
}

const ErrorRouteWithChildren = ErrorRoute._addFileChildren(ErrorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  R2faRoute: R2faRoute,
  AppRoute: AppRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  ErrorRoute: ErrorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionLockedRoute: SessionLockedRoute,
  SignupRoute: SignupRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
